### ISSUE TITLE
Devolución de artículos

### ISSUE THREAD

**Issue by Fonx95** [Fonx95/PGPI20-21-equipo-27#2]
Creación de un sistema de devoluciones, funcionalidad que debe permitir devolver un artículo y su forma de devolución de importe

**Comment by alorodlla** [comment]
Debido a un malentendido entre el jefe de proyecto y uno de los miembros del equipo, se señalo esta issue como "excluida", a pesar de haberse realizado. Se ha corregido este error y se ha añadido la actividad a su columna correspondiente.
